profiles:

  # Based on Ofcom's research into the bandwidth and latency of 4G and 3G
  # networks in the UK in 2015
  # (see http://stakeholders.ofcom.org.uk/market-data-research/other/telecoms-research/broadband-speeds/mobile-bb-april-15/).
  - name: '4G (UK)'
    bandwidth: # (Mbit/s)
      download: 14.7
      upload: 13.6
    round_trip_time: 53.1 # (ms)

  - name: '3G (UK)'
    bandwidth:
      download: 5.9
      upload: 1.6
    round_trip_time: 63.5
